rss: rss.xml
name: njms blog
description: A blog, by njms, about development and other things
link: https://njms.ca
source: _src
drafts: _drafts
excerpt_separator: <span data-separator></span>
ignore:
  - .git/*
  - build/*
  - README.md
  - LICENSE
